<?php

namespace DWBD\RistauranteBundle\Repository;

use \Doctrine\ORM\EntityRepository;
use \Doctrine\DBAL\Exception\InvalidArgumentException;

/**
 * DishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DishRepository extends EntityRepository
{
}
